#!/bin/bash

[ $# -ne 1 ] && echo "usage: $0 <message>" && exit 1

echo '''<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>jBravo</title>
        <script src="static/jbravo.js"></script>
        <link rel="stylesheet" href="static/jbravo.css">
    </head>
    <body onload="enableLockByDate()">'''

d=$(date +%d-%m-%Y)
for i in $(seq ${#1}); do
  c=$(echo "${1:i-1:1}")
  [[ ${c} == " " ]] && o=0 || o=$(printf '%d\n' "'$c")
  echo "          <div class=\"flex-container\" id=\"${d}\">"
  echo "              <div class=\"letter\" id=\"${d}-letter\">—</div>"
  echo "              <div class=\"count-current\" id=\"${d}-count-current\">0</div>"
  echo "              /"
  echo "              <div class=\"count-target\" id=\"${d}-count-target\">${o}</div>"
  echo "              <label>"
  echo "                  <input class=\"done\" id=\"${d}-done\" type=\"text\" value=\"0\" disabled>"
  echo "              </label>"
  echo "              <input class=\"update\" id=\"${d}-update\" type=\"submit\" value=\"update\" disabled onclick=\"update('${d}');\">"
  echo "          </div>"
done

echo '''    </body>
</html>'''

