#!/bin/bash

[ $# -ne 1 ] && echo "usage: $0 <message>" && exit 1

f=$(date +%d-%m-%Y)-$(echo ${1} | base64).html
echo '''<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>jBravo</title>
        <script src="static/jbravo.js"></script>
        <link rel="stylesheet" href="static/jbravo.css">
    </head>
    <body onload="enableLockByDate()">''' > ${f}

for i in $(seq ${#1}); do
  d=$(date +%d-%m-%Y -d "+$((i-1)) days")
  c=$(echo "${1:i-1:1}")
  [[ ${c} == " " ]] && o=0 || o=$(printf '%d\n' "'$c")
  echo -e "          <div class=\"flex-container\" id=\"${d}\">\n              <div class=\"letter\" id=\"${d}-letter\">—</div>\n              <div class=\"count-current\" id=\"${d}-count-current\">0</div>\n              /\n              <div class=\"count-target\" id=\"${d}-count-target\">${o}</div>\n              <label>\n                  <input class=\"done\" id=\"${d}-done\" type=\"text\" value=\"0\" disabled>\n              </label>\n              <input class=\"update\" id=\"${d}-update\" type=\"submit\" value=\"update\" disabled onclick=\"update('${d}');\">\n          </div>" >> ${f}
done

echo '''    </body>
</html>''' >> ${f}

